install(
    FILES
        Splash.qml
        metadata.desktop
    DESTINATION
        ${KDE_INSTALL_DATADIR}/ksplash/Themes/Maia
)

install(
    FILES
        images/busywidget.svgz
        images/kde.svgz
        images/manjaro.svgz
    DESTINATION
        ${KDE_INSTALL_DATADIR}/ksplash/Themes/Maia/images
)
